// 各类型对象可编辑的属性
// 用于 AttributeEditor 组件的显示

export const canvas = {
  left: false,
  top: false,
  height: false,
  width: false,
  angle: false,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: false,
  strokeWidth: false,
  obrType: false,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:true,
  ruler:true,
  gridColor: true,
  backgroundColor: true,
  backgroundHeight: true,
  backgroundWidth: true,
  stroke: false,
  fill: false,
  textBackgroundColor: false,
  layer: false,
  strokeDashArray: false,

  name:false,

  //右键菜单操作控制
  copy:true,
  paste:false,
  Value:true,
  TextDynamics:true,
  Length:true,
  Color:true,
  Visible:true,
  Mapping:true,
  Set:true,
  Setdyna:true,
  Add:true,
  Go:true,
  Open:true,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}

export const line = {
  left: true,
  top: true,
  height: false,
  width: false,
  angle: true,
  length: true,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: true,
  strokeWidth: true,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: true,
  fill: false,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray: true,

  name:true,


  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}
export const triangle = {
  left: true,
  top: true,
  height: true,
  width: true,
  angle: true,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: true,
  strokeWidth: true,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: true,
  fill: true,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray: true,

  name:true,


  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}
export const rect = {
  left: true,
  top: true,
  height: true,
  width: true,
  angle: true,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: true,
  strokeWidth: true,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: true,
  fill: true,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray:true,

  name:true,


  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,

}
export const circle = {
  left: true,
  top: true,
  height: false,
  width: false,
  angle: true,
  length: false,
  radius: true,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: true,
  strokeWidth: true,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: true,
  fill: true,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray: true,

  name:true,


  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}
export const ellipse = {
  left: true,
  top: true,
  height: false,
  width: false,
  angle: true,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: true,
  rx: true,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: true,
  strokeWidth: true,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: true,
  fill: true,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray: true,

  name:true,


  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}
export const iText = {
  left: true,
  top: true,
  height: false,
  width: false,
  angle: true,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: true,
  fontSize: true,
  charSpacing: true,
  text: true,
  opacity: true,
  strokeWidth: false, 
  obrType: true,
  textAlign: true,
  fontFamily: true,
  bold: true,
  italic: true,
  underline: true,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: true,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: true,
  fill: true,
  textBackgroundColor: true,
  layer: true,
  strokeDashArray: false,

  name:true,


  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:false,
  TextDynamics:false,
  Length:true,
  Color:false,
  Visible:false,
  Mapping:false,
  Set:true,
  Setdyna:true,
  Add:true,
  Go:true,
  Open:true,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}
export const polygon = {
  left: true,
  top: true,
  height: true,
  width: true,
  angle: true,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: true,
  strokeWidth: true,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: true,
  fill: true,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray:true,

  name:true,



  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}
export const polyline = {
  left: true,
  top: true,
  height: true,
  width: true,
  angle: true,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: true,
  strokeWidth: true,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: true,
  fill: false,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray:true,

  name:true,


  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}
export const curve = {
  left: true,
  top: true,
  height: true,
  width: true,
  angle: true,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: true,
  strokeWidth: true,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: true,
  fill: false,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray:true,

  name:true,


  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}

//sector's underlying obrType in fabric
export const sector = {
  left: true,
  top: true,
  height: false,
  width: false,
  angle: true,
  length: false,
  radius: false,
  startAngle: true,
  endAngle: true,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: true,
  strokeWidth: true,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: true,
  fill: true,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray: true,

  name:true,


  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}
export const group = {
  left: true,
  top: true,
  height: true,
  width: true,
  angle: true,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: false,
  strokeWidth: false,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: false,
  fill: false,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray: false,

  name:true,


  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:false,
  moveUp:false,
  moveDown:false,
  toBottom:false,
  group:true,
  ungroup:false,
}

export const tempGroup = {
  left: true,
  top: true,
  height: true,
  width: true,
  angle: true,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: false,
  strokeWidth: false,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: false,
  fill: false,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray: false,

  name:false,



  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:false,
  horizontalAlign:false,
  rightAlign:false,
  topAlign:false,
  verticalAlign:false,
  bottomAlign:false,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:false,
  ungroup:true,
}

export const image = {
  left: true,
  top: true,
  height: true,
  width: true,
  angle: true,
  length: false,
  radius: false,
  startAngle: false,
  endAngle: false,
  ry: false,
  rx: false,
  lineHeight: false,
  fontSize: false,
  charSpacing: false,
  text: false,
  opacity: true,
  strokeWidth: false,
  obrType: true,
  textAlign: false,
  fontFamily: false,
  bold: false,
  italic: false,
  underline: false,
  grid:false,
  ruler:false,
  gridColor: false,
  backgroundColor: false,
  backgroundHeight: false,
  backgroundWidth: false,
  stroke: false,
  fill: false,
  textBackgroundColor: false,
  layer: true,
  strokeDashArray: false,

  name:true,
  

  //右键菜单操作控制
  copy:false,
  paste:true,
  Value:true,
  TextDynamics:true,
  Length:false,
  Color:false,
  Visible:false,
  Mapping:true,
  Set:false,
  Setdyna:false,
  Add:false,
  Go:false,
  Open:false,
  leftAlign:true,
  horizontalAlign:true,
  rightAlign:true,
  topAlign:true,
  verticalAlign:true,
  bottomAlign:true,
  toFront:true,
  moveUp:true,
  moveDown:true,
  toBottom:true,
  group:true,
  ungroup:true,
}