// add shape primitive to canvas
export const ADD = 'ADD'


export const ADDNUM = 'ADDNUM'


//set attribute
export const SET_ATTRIBUTE_LEFT = 'SET_ATTRIBUTE_LEFT' 
export const SET_ATTRIBUTE_TOP = 'SET_ATTRIBUTE_TOP' 
export const SET_ATTRIBUTE_HEIGHT = 'SET_ATTRIBUTE_HEIGHT' 
export const SET_ATTRIBUTE_WIDTH = 'SET_ATTRIBUTE_WIDTH' 
export const SET_ATTRIBUTE_ANGLE = 'SET_ATTRIBUTE_ANGLE' 
export const SET_ATTRIBUTE_LENGTH = 'SET_ATTRIBUTE_LENGTH' 
export const SET_ATTRIBUTE_RADIUS = 'SET_ATTRIBUTE_RADIUS' 
export const SET_ATTRIBUTE_START_ANGLE = 'SET_ATTRIBUTE_START_ANGLE'
export const SET_ATTRIBUTE_END_ANGLE = 'SET_ATTRIBUTE_END_ANGLE' 
export const SET_ATTRIBUTE_RY = 'SET_ATTRIBUTE_RY'  
export const SET_ATTRIBUTE_RX = 'SET_ATTRIBUTE_RX' 
export const SET_ATTRIBUTE_LINE_HEIGHT = 'SET_ATTRIBUTE_LINE_HEIGHT' 
export const SET_ATTRIBUTE_FONT_SIZE = 'SET_ATTRIBUTE_FONT_SIZE' 
export const SET_ATTRIBUTE_CHARACTER_SPACE = 'SET_ATTRIBUTE_CHARACTER_SPACE' 
export const SET_ATTRIBUTE_TEXT_CONTENT = 'SET_ATTRIBUTE_TEXT_CONTENT' 
export const SET_ATTRIBUTE_OPACITY = 'SET_ATTRIBUTE_OPACITY' 
export const SET_ATTRIBUTE_STROKE_WIDTH = 'SET_ATTRIBUTE_STROKE_WIDTH' 
export const SET_ATTRIBUTE_TYPE = 'SET_ATTRIBUTE_TYPE' 
export const SET_ATTRIBUTE_STROKE_DASH_ARRAY = 'SET_ATTRIBUTE_STROKE_DASH_ARRAY' 
export const SET_ATTRIBUTE_TEXT_ALIGN = 'SET_ATTRIBUTE_TEXT_ALIGN' 
export const SET_ATTRIBUTE_FONT_FAMILY = 'SET_ATTRIBUTE_FONT_FAMILY' 
export const SET_ATTRIBUTE_BOLD = 'SET_ATTRIBUTE_BOLD' 
export const SET_ATTRIBUTE_ITALIC = 'SET_ATTRIBUTE_ITALIC' 
export const SET_ATTRIBUTE_UNDERLINE = 'SET_ATTRIBUTE_UNDERLINE' 
export const SET_ATTRIBUTE_GRID_VISIBILITY = 'SET_ATTRIBUTE_GRID_VISIBILITY' 
export const SET_ATTRIBUTE_RULER_VISIBILITY = 'SET_ATTRIBUTE_RULER_VISIBILITY' 
export const SET_ATTRIBUTE_GRID_COLOR = 'SET_ATTRIBUTE_GRID_COLOR' 
export const SET_ATTRIBUTE_BACKGROUND_COLOR = 'SET_ATTRIBUTE_BACKGROUND_COLOR' 
export const SET_ATTRIBUTE_STROKE = 'SET_ATTRIBUTE_STROKE' 
export const SET_ATTRIBUTE_FILL = 'SET_ATTRIBUTE_FILL'
export const SET_ATTRIBUTE_TEXT_BACKGROUND_COLOR = 'SET_ATTRIBUTE_TEXT_BACKGROUND_COLOR' 
export const SET_ATTRIBUTE_LAYER = 'SET_ATTRIBUTE_LAYER'


export const SET_ATTRIBUTE_NAME = 'SET_ATTRIBUTE_NAME'


// set attributes
export const SET_ATTRIBUTES = "SET_ATTRIBUTES"


// set form-items visibility
export const SET_FORM_ITEMS_VISIBILITY = 'SET_FORM_ITEMS_VISIBILITY'


// File.vue
export const FILE_SIGNAL = 'FILE_SIGNAL'


// Edit.vue component mutations-types
export const EDIT_SIGNAL = 'EDIT_SIGNAL'


// Scene.vue
export const SCENE_SIGNAL = 'SCENE_SIGNAL'
// export const SCENE_TOGGLE = 'SCENE_TOGGLE'


// Arrange.vue component mutations-types
export const ARRANGE_SIGNAL = 'ARRANGE_SIGNAL'


// config.js
export const UPDATE_CONFIG = 'UPDATE_CONFIG'


// background.js
export const SET_BACKGROUND_HEIGHT = 'SET_BACKGROUND_HEIGHT'
export const SET_BACKGROUND_WIDTH = 'SET_BACKGROUND_WIDTH'
export const SET_BACKGROUND_ZOOM = 'SET_BACKGROUND_ZOOM'


// 记录文件是否保存
export const SET_SAVE_STATUS = 'SET_SAVE_STATUS'




//popup add attribute
export const SET_SHOW_POPUP='SET_SHOW_POPUP'
export const SET_ATTR_DATA='SET_ATTR_DATA'
export const SET_POP_NAME='SET_POP_NAME'

export const SET_RIGHT_SHOW='SET_RIGHT_SHOW'




//树形结构
export const SET_TREE='SET_TREE'
export const SET_TREE_TITLE='SET_TREE_TITLE'
